# Generated by Django 5.2.4 on 2025-07-23 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number1', models.FloatField(verbose_name='Número 1')),
                ('number2', models.FloatField(verbose_name='Número 2')),
                ('operation_type', models.CharField(choices=[('soma', 'Soma'), ('subtracao', 'Subtração'), ('multiplicacao', 'Multiplicação'), ('divisao', 'Divisão')], max_length=20, verbose_name='Tipo de Operação')),
                ('result', models.FloatField(verbose_name='Resultado')),
                ('operation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data da Operação')),
                ('default_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Operação',
                'verbose_name_plural': 'Operações',
                'ordering': ['-operation_date'],
            },
        ),
    ]
